### ISSUE TITLE
Distribution with existing folder structure

### ISSUE THREAD

**Issue by fishmi** [aileen-r/parcel-html-sass-js-starter-template#2]
Hello Aileen,

Thank you for the great starter template. It makes getting started with Parcel much easier.

However, I am getting desperate with the following requirement:
I would like to build the same folder structure (with assets, js, css) in the dist folder as in the src folder, but I just can't get it to work. 
I have already done a lot of research and tried out various tips and plug-ins, but have not found a working solution.
Do you have a working solution for this?
I'm always surprised that this isn't a standard in parcel, because I don't work on a project where the sources should all be in the same folder.
Thank you very much.

Kind regards 
Martin

**Comment by aileen-r** [comment]
@fishmi [The feature has been requested](https://github.com/parcel-bundler/parcel/issues/233), but sadly no, Parcel doesn't support custom `dist` folder structures out of the box.

You would have to write a plugin that does this for you. As far as I am aware there is no plugin out there that supports version 2, only [this one for Parcel v1](https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure).

**Comment by fregante** [comment]
I'm using https://www.npmjs.com/package/@mischnic/parcel-namer-preserve-structure

You can find alternatives among the namer plugins:

https://parceljs.org/plugin-browser/?type=%22namer%22&page=0&filter=%22%22&includeOfficial=false
